### PR TITLE
Palette suffixes to prefixes

### PR DESCRIPTION
**Pull request by teunbrand**
This PR aims to fix https://github.com/r-lib/scales/issues/390#issuecomment-1641643638.

Briefly, it renames all `*_pal` functions to `pal_*` functions, while keeping the suffixed versions as aliases.

### CODE REVIEW

**Comment by thomasp85** [comment]
Can I get you to fix conflicts

**Comment by teunbrand** [comment]
Done. These conflicts after renaming files from `.r` to `.R` are my least favourite conflicts so far.

**Comment by thomasp85** [comment]
I can imagine 😅

**Comment by thomasp85** [comment]
Thanks

**Pull request merged**
