### PR TITLE
label_number_si: Fix k and G, and add P, E, Z, Y

### PR DESCRIPTION
**Pull request by sjackman**
See https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes

### CODE REVIEW

**Comment by sjackman** [comment]
Thank you very much for `scales`! It's the fifth-most common R package that I use, after `readr`, `tidyr`, `dplyr`, and `ggplot2`. 🌟

**Comment by sjackman** [comment]
Would someone have time to review this PR, please?

**Comment by mikmart** [comment]
I think this has been discussed in #234  and would also be fixed by #235.

**Comment by sjackman** [comment]
Cool. Feel free to close in favour of PR https://github.com/r-lib/scales/pull/235

**Comment by davidchall** [comment]
Hi @sjackman - this was fixed by #235.

**Comment by sjackman** [comment]
Thank you, David! ✨
Superseded by #235.

**Pull request closed without merging**
